#Note: This file may not work.
version: '3.1'

services:
  leberkasrechner:
    image: leberkasrechner
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_DB: your_mysql_db

  db:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_db
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
